### ISSUE TITLE
建议项目介绍中移除代码优雅的描述

### ISSUE THREAD

**Issue by laobie** [HuTianQi/QQ#3]
![image](https://cloud.githubusercontent.com/assets/7184320/20856849/da4256cc-b955-11e6-87bb-55a07ac0bb9a.png)
这是你的 MainActivity 的部分代码截图。所以提出此建议。

**Comment by laobie** [comment]
至于项目中大部分都是字符串硬编码就不多说了。

**Comment by ZhangLanqiu** [comment]
@laobie 。。。。。。人家写个程序也不容易

**Comment by laobie** [comment]
@ZhangLanqiu 不容易归不容易，标准在那

**Comment by ysmintor** [comment]
赞同！标题太夸大了！接收建议吧！

**Comment by Chenantao** [comment]
看到这条 issue 害我一大早在公司发出杠铃般的笑声

**Comment by Lsy1992** [comment]
哈哈哈哈红红火火恍恍惚惚

**Comment by Lsy1992** [comment]
貌似用EventBus接收事件传值优雅点？

**Comment by 1169458576** [comment]
哈哈笑死了

**Comment by laobie** [comment]
@Lsy1992 你要知道，这个项目可能还是 eclipse 开发的

**Comment by Lsy1992** [comment]
不知道作者看没看到啊？还是故意不出来回复

**Comment by Lsy1992** [comment]
@laobie 仔细一看这个项目的结构，还真的不是AS开发的哦

**Comment by mlick** [comment]
eclipse？  
![qq 20161205110500](https://cloud.githubusercontent.com/assets/8747500/20872581/b4c9eb68-bada-11e6-9f7e-b1ab3ecf3539.png)

**Comment by brucezz** [comment]
![image](https://cloud.githubusercontent.com/assets/15318754/20872766/3d63ae9a-badc-11e6-965e-fd2fe9c3d077.png)

乱码了诶，不知道作者发现了没。
还有 `class ActivityBase extends BaseActivity` 是什么鬼😂

**Comment by nevermore1000** [comment]
十分优雅，满分💯

**Comment by itsMelo** [comment]
我想问下作者 eclipse GBK 代码没格式化，类功能冗余，变量蜜汁命名，这一坨坨的代码看起来确实赏心悦目，总之气氛突然优雅了起来。

**Comment by Lsy1992** [comment]
就这代码还有300+的star

**Comment by laobie** [comment]
![image](https://cloud.githubusercontent.com/assets/7184320/20878133/fcc0867a-bb07-11e6-857c-cff13e3e4f2f.png)

**Comment by brucezz** [comment]
@Lsy1992 
![image](https://cloud.githubusercontent.com/assets/15318754/20878158/3a5918a8-bb08-11e6-8e63-08a9012606ed.png)

粘贴图片就好了

**Comment by Lsy1992** [comment]
我黏贴不行呢 @brucezz

**Comment by itsMelo** [comment]
作者你好，我在你的另一个项目里看到了一个叫 FragmentAndActivity 的接口，这样的命名让人无语凝噎，我不知道想说什么想打什么字，总之，谢谢你。

**Comment by Lsy1992** [comment]
作者都吓得不敢出来

**Comment by mlick** [comment]
@Lsy1992  直接把图片拖到评论框就行
![Uploading 201403301229017093.gif…]()

**Comment by mlick** [comment]
@Lsy1992 直接把图片拖到评论框就行
![Uploading 201403301229017093.gif…]()

**Comment by Lsy1992** [comment]
![1gk1rtuq s5_ z 3 4nnglc](https://cloud.githubusercontent.com/assets/12758497/20878386/93fe05ca-bb09-11e6-9333-c1da67e7b59f.gif)  哈哈，着issues是不是太过于欢乐了

**Comment by mlick** [comment]
擦，我的gif竟然没上传成功

**Comment by brucezz** [comment]
或者用 markdown 语法就好了，贴好图片 url

**Comment by yongyu0102** [comment]
![hids qvmw yfyp5akbm](https://cloud.githubusercontent.com/assets/13392987/20878486/31fe0040-bb0a-11e6-89fc-ce3bf93e1068.gif)
会玩

**Comment by AriaLyy** [comment]
在稀土上看到的，十分优雅，还以为代码有多牛逼，特来观摩学习，奈何，一打开issues就把我笑喷了

**Comment by 1169458576** [comment]
`
[https://cloud.githubusercontent.com/assets/13392987/20878486/31fe0040-bb0a-11e6-89fc-ce3bf93e1068.gif](url)

**Comment by 1169458576** [comment]
![](https://cloud.githubusercontent.com/assets/13392987/20878486/31fe0040-bb0a-11e6-89fc-ce3bf93e1068.gif)

**Comment by mlick** [comment]
![201403301229017093](https://cloud.githubusercontent.com/assets/8747500/20879382/78ec4102-bb0e-11e6-9b6a-a3814ed54db0.gif) 
好 成功了！

**Comment by bestTao** [comment]
这条issue比项目的代码要优雅得多啊

**Comment by 13259445198** [comment]
总之issues把eclisps的优雅代替了  哈哈

**Comment by vincepy** [comment]
![koala](https://cloud.githubusercontent.com/assets/8514361/20951323/0b5eb734-bc60-11e6-911d-822f673bbc24.jpg)

**Comment by north2016** [comment]
![c529e99b20833c2198080909a09335ea](https://cloud.githubusercontent.com/assets/7598555/20954716/a34b9b80-bc78-11e6-971d-b7535155b8fb.gif)

**Comment by north2016** [comment]
![7dfb45452b85b7761ff8ee97beb100fd](https://cloud.githubusercontent.com/assets/7598555/20954739/e29e45bc-bc78-11e6-8669-25c7b1258e3b.gif)


要优雅

**Comment by ysmintor** [comment]
![screenshot_2016-08-17-22-08-57-503_com xiaomi shop](https://cloud.githubusercontent.com/assets/7165048/20956925/d8f696a4-bc87-11e6-94d9-33f548cf333f.png)
学习到了图片还可以这样保证的啊？不错

**Comment by renhui** [comment]
好玩，我过来凑合热闹！！！！ 要优雅！！！！

**Comment by kylesean** [comment]
```
echo "要优雅！";
```

**Comment by hezhiming** [comment]
@laobie  好欢乐啊!

**Comment by godzoco** [comment]
要优雅！！！！

**Comment by laobie** [comment]
@hezhiming 作者不出来回应，楼就歪了 = =
![image](https://cloud.githubusercontent.com/assets/7184320/20970322/f7039ecc-bcc7-11e6-93cf-3d50c3bfebae.png)

**Comment by ZhouHoubin** [comment]
这也算高仿吗,就改改别人sdk 的demo

**Comment by iwuq** [comment]
你们硬生生把一个issues变成了一个聊天室...

**Comment by whthomas** [comment]
看来还不会用快速format的快捷键啊。

**Comment by ding102992** [comment]
花括号一会换行，一会不换行，不能忍啊。要优雅。

**Comment by Lsy1992** [comment]
大家散了吧，楼主（作者）已经卷钱跟小姨子跑啦！

**Comment by yhhwpp** [comment]
hahaha

**Comment by YeungKC** [comment]
![d4c925f5efa6026ab6e07bb8fdb4ee0a](https://cloud.githubusercontent.com/assets/11473691/21040582/da009a28-be20-11e6-83d7-4d0e94541534.jpg)
要优雅

**Comment by hymanme** [comment]
谢谢你的代码。
![g poj gxuml 03q0gpt 3 g](https://cloud.githubusercontent.com/assets/10279568/21040597/ef16a3a8-be20-11e6-8954-3e2a488cff1d.jpg)

**Comment by haocity** [comment]
我就看着邮件一封封的,,,,这是issues好不好

**Comment by yhhwpp** [comment]
@haocity  你可以取消订阅 吼吼

**Comment by bestTao** [comment]
作者在Readme文件中添加了微信和支付宝的二维码啦，大家优雅的打赏吧
![image](https://cloud.githubusercontent.com/assets/16660255/21133084/11f21f36-c152-11e6-83b9-46a5644466be.png)

**Comment by bestTao** [comment]
直接关了，厉害

**Comment by laobie** [comment]
原来关闭了还可以回复

**Comment by Lsy1992** [comment]
我感觉作者有点不要脸啊， 大家好心给提出不足，他不但不悔改，还无耻的放出付款二维码？？什么鬼啊？！

**Comment by 1169458576** [comment]
描述这也没改啊，强行无视...

**Comment by hymanme** [comment]
怎么？想把QQ干下去啊？😳😳😳

发自我的 iPhone

**Comment by Lsy1992** [comment]
![amlx_p0j 39 fkwk sbqm](https://cloud.githubusercontent.com/assets/12758497/21217437/2f2e90c0-c2e7-11e6-8ab4-ebb0a089c989.png) 大家给作者一点面子，要不然在这样嘲笑下去，他估计都要注销GitHub了...hhh

**Comment by lwllovewf2010** [comment]
oh, What happened?

**Comment by YaoDanLiu** [comment]
凑热闹 2333

**Comment by G159Z** [comment]
笑死我了 这就是个demo加上一个抽屉嘛，还指望打赏，哈哈哈哈。😄

**Comment by bluishoul** [comment]
@YaoDanLiu 蛋蛋

**Comment by bestTao** [comment]
@laobie 被关的issue还是能回复，只不过整个issue在项目中就不显眼，而且被作者关了就不能重新打开了，不过可以另开一个issue 指向这个issue
