### ISSUE TITLE
我如果用的jni的方式如何引入呢？

### ISSUE THREAD

**Issue by tianshaokai** [HuTianQi/QQ#9]
1. 如题

**Comment by HuTianQi** [comment]
这个库解决的主要是OpenCV官方SDK Android端的图像预览问题，Java层调用摄像头做图像采集，采集到的数据送到native层做图像处理。你说的JNI引入是指对采集的图像数据做处理吧，这些直接用OpenCV官方SDK的C++层接口即可，可以参看Demo中的Cpp文件。也可以参看OpenCV官方的一些Demo示例

**Comment by tianshaokai** [comment]
对，主要是我看你用的是java opencv sdk 的方式，我没有使用java sdk，而是直接用的jni 的方式
